### ISSUE TITLE
Daily accumulated Rewards

### ISSUE THREAD

**Issue by SpecialAgentX** [geldmacher/Cake-to-CoinTracking-Converter#1]
Hey,

thank you for developing such a tool.

It would be nice, if your tool could offer an option to save count of transactions. In my opinion it would be sufficient to accumulate all rewards from one product (staking, Liquidity Mining) on a daily basis. 

The screenshot shows the result for 31th Dec. 2020. Green shows staking rewards and blue Liquidity Mining Rewards for that day (of all LM-Pools).

<img width="240" alt="Bildschirmfoto 2021-04-11 um 15 54 28" src="https://user-images.githubusercontent.com/24278992/114307117-7fa6ff00-9ade-11eb-9130-3571a5cd5966.png">

This could be accumulated to 2 transactions. Otherwise I need to import 356 transcations for just one month, where I did not really a lot at Cake. CoinTracking is limited to 3500 transaction for PRO users and thus I would need to upgrade in 10 months.

So, please add this function. I'd really appreciate this. 

Thanks

**Comment by geldmacher** [comment]
Hi, 

thanks for this kind and detailed issue! =)

I had this function in previous versions. There were a lot more of this transactions in older Cake exports. I rolled it back because they are now way less. 

There are some caveats.

1. I need to generate a transaction with an unique identifer Cake does not know. So there is no clean way to swicth between theses approaches. Otherwiese CoinTracking would be flooed with fals transactions. You have to stick to the way you import data. Or you switch it at certain dates and move forward with the other approach from there on.
2. I need to accumulate the values (Coin + FIAT [if you choose to use Cake's FIAT valuation]) for a fixed time and date. It would be 0 o'clock each day this way. So i would merge them into a single transaction. This means that the data is not 100% correct anymore. 

But i will reintroduce it behind a optional feature flag. Perhaps i will use it again for my self, too. =)
I switched because i needed to upgrade my CoinTracking plan anyways.

Atm there is not that much time left, but i will do it. Keep an eye on this issue! =)

**Comment by geldmacher** [comment]
@SpecialAgentX Please try version 3.0.0 and give me some feedback. Additional infos: https://github.com/geldmacher/Cake-to-CoinTracking-Converter/releases/tag/v3.0.0

**Comment by geldmacher** [comment]
Seems like it is working!? Please reopen this issue if this is still a problem.
